---
- name: Install Docker and Run Jenkins Server
  hosts: all
  become: yes
  tasks:
    - name: Remove existing Docker/containerd if present
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - docker.io
        - docker-ce
        - containerd
        - containerd.io

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker-ce

    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Jenkins Docker image
      docker_image:
        name: jenkins/jenkins
        source: pull

    - name: Run Jenkins container
      docker_container:
        name: Jenkins_container
        image: jenkins/jenkins
        state: started
        ports:
          - "8080:8080"
        volumes:
          - jenkins_data:/var/jenkins_home
        restart_policy: unless-stopped
        detach: true
